AWSTemplateFormatVersion: 2010-09-09
Description: Sample template that sends S3 bucket event notifications to EventBridge 

#-----------
Parameters:
#-----------
  MyEmailAddress:
    Description: Email address to subscribe to SNS topic
    Type: String

#-----------
Resources:
#-----------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  EventsRule:
    Type: AWS::Events::Rule
    Properties:
      Description: !Sub 'Events on bucket s3://${S3Bucket}'
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Access Tier Changed
          - Object ACL Updated
          - Object Created
          - Object Deleted
          - Object Restore Completed
          - Object Restore Expired
          - Object Restore Initiated
          - Object Storage Class Changed
          - Object Tags Added
          - Object Tags Deleted
        detail:
          bucket:
            name:
              - !Ref S3Bucket
      State: ENABLED
      Targets: 
        - Arn: !Ref SNSTopic
          Id: EventTopic

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref MyEmailAddress
          Protocol: email

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: AWSEvents_Permission
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sns:Publish
            Resource: !Ref SNSTopic
      Topics:
        - !Ref SNSTopic

#-----------
Outputs:
#-----------
  S3BucketName:
    Value: !Ref S3Bucket
    Description: Name of the sample Amazon S3 bucket with a notification configuration to EventBridge