AWSTemplateFormatVersion: 2010-09-09
Description: Sample template that creates an S3 bucket with a unique name

#-----------
Parameters:
#-----------
  BucketPrefix:
    Description: Value that will be prefixed to the bucket name (letters must be in lowercase)
    Type: String
    AllowedPattern: '^[a-z0-9][a-z0-9-.]+$'
    ConstraintDescription: Must only contain lowercase letters, numbers, periods (.), and dashes (-) and it must begin with a letter or number.

#-----------
Resources:
#-----------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join 
        - '-'
        - - !Ref BucketPrefix
          - !Ref AWS::AccountId
          - !Ref AWS::Region
          - 'bucket'
          - !Select 
            - 0
            - !Split 
              - '-'
              - !Select 
                - 2
                - !Split 
                  - /
                  - !Ref AWS::StackId

#-----------
Outputs:
#-----------
  S3Bucket:
    Value: !Ref S3Bucket
