AWSTemplateFormatVersion: 2010-09-09
Description: Sample template that creates an S3 bucket with basic security settings

#-----------
Resources:
#-----------
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: Deny
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}/*
              - !Sub arn:aws:s3:::${S3Bucket}
            Principal: '*'
            Condition:
              Bool:
                  'aws:SecureTransport': 'false'

#-----------
Outputs:
#-----------
  S3Bucket:
    Value: !Ref S3Bucket
