AWSTemplateFormatVersion: 2010-09-09
Description: Specifies a user for an Amazon Connect instance (with SAML 2.0-based authentication)

#-----------
Parameters:
#-----------
  ConnectInstanceId:
    Description: Amazon Connect instance id
    Type: String

  ConnectRoutingProfileId:
    Description: Amazon Connect routing profile id
    Type: String

  ConnectSecurityProfileId:
    Description: Amazon Connect security profile id
    Type: String

#-----------
Resources:
#-----------
    User:
      Type: 'AWS::Connect::User'
      Properties:
        IdentityInfo:
          FirstName: 'firstname'
          LastName: 'lastname'
#          Email: 'example@email.com'
        PhoneConfig:
          PhoneType: 'SOFT_PHONE'
          AutoAccept: false
          AfterContactWorkTimeLimit: 30
        Username: 'exampleuserCFN'
        InstanceArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}'
        RoutingProfileArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/routing-profile/${ConnectRoutingProfileId}'
        SecurityProfileArns: [!Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/security-profile/${ConnectSecurityProfileId}'] 
#        Password: !Ref password
        Tags:
          - Key: 'tagKey'
            Value: 'tagValue'