AWSTemplateFormatVersion: 2010-09-09
Description: Specifies a user hierarchy group for an Amazon Connect instance

#-----------
Parameters:
#-----------
  ConnectInstanceId:
    Description: Amazon Connect instance id
    Type: String

#-----------
Resources:
#-----------
  HierarchyGroupLevel1:
    Type: AWS::Connect::UserHierarchyGroup
    Properties: 
      Name: 'exampleUserHierarchyGroupLevel1CFN'
      InstanceArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}'

  HierarchyGroupLevel2:
    Type: 'AWS::Connect::UserHierarchyGroup'
    Properties:
      Name: 'exampleUserHierarchyGroupLevel2CFN'
      InstanceArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}'
      ParentGroupArn: !GetAtt HierarchyGroupLevel1.UserHierarchyGroupArn