AWSTemplateFormatVersion: 2010-09-09
Description: Specifies an hours of operation for an Amazon Connect instance

#-----------
Parameters:
#-----------
  ConnectInstanceId:
    Description: Amazon Connect instance id
    Type: String

  ConnectContactFlowIdTransferToAgent:
    Description: Amazon Connect contact flow id (transfer to agent)
    Type: String

  ConnectUserId:
    Description: Amazon Connect user id
    Type: String

#-----------
Resources:
#-----------
  QuickConnectUser:
    Type: AWS::Connect::QuickConnect
    Properties: 
      Description: 'quick connect created using cfn'
      InstanceArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}'
      Name: 'QuickConnectCFN'
      QuickConnectConfig: 
        QuickConnectType: USER
        UserConfig: 
          ContactFlowArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/contact-flow/${ConnectContactFlowIdTransferToAgent}'
          UserArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/agent/${ConnectUserId}'
      Tags:
        - Key: 'tagKey'
          Value: 'tagValue'