AWSTemplateFormatVersion: 2010-09-09
Description: Specifies an hours of operation for an Amazon Connect instance

#-----------
Parameters:
#-----------
  ConnectInstanceId:
    Description: Amazon Connect instance id
    Type: String

#-----------
Resources:
#-----------
  HoursOfOperation:
    Type: 'AWS::Connect::HoursOfOperation'
    Properties:
      Name: 'RegularHoursOfOperationCFN'
      Description: 'hours of operation created using cfn'
      InstanceArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}'
      TimeZone: 'America/Los_Angeles'
      Config:
        - Day: 'MONDAY'
          StartTime:
            Hours: 8
            Minutes: 00
          EndTime:
            Hours: 17
            Minutes: 00
        - Day: 'TUESDAY'
          StartTime:
            Hours: 8
            Minutes: 00
          EndTime:
            Hours: 17
            Minutes: 00
        - Day: 'WEDNESDAY'
          StartTime:
            Hours: 8
            Minutes: 00
          EndTime:
            Hours: 17
            Minutes: 00
        - Day: 'THURSDAY'
          StartTime:
            Hours: 8
            Minutes: 00
          EndTime:
            Hours: 17
            Minutes: 00
        - Day: 'FRIDAY'
          StartTime:
            Hours: 8
            Minutes: 00
          EndTime:
            Hours: 17
            Minutes: 00
        - Day: 'SATURDAY'
          StartTime:
            Hours: 8
            Minutes: 00
          EndTime:
            Hours: 12
            Minutes: 00
      Tags:
        - Key: 'tagKey'
          Value: 'tagValue'