AWSTemplateFormatVersion: 2010-09-09
Description: Creates a contact flow for Amazon Connect instance

#-----------
Parameters:
#-----------
  ConnectInstanceId:
    Description: Amazon Connect instance id
    Type: String

  ConnectQueueId:
    Description: Amazon Connect queue id
    Type: String

#-----------
Resources:
#-----------
  ContactFlow:
    Type: 'AWS::Connect::ContactFlow'
    Properties:
      Name: Basic contact call flow [CFN]
      Description: Contact flow created using cfn
      InstanceArn: !Sub 'arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}'
      Type: CONTACT_FLOW
      Content: !Sub >-
        {"Version":"2019-10-30","StartAction":"590ad770-653e-4368-9153-ab6801067f10","Metadata":{"entryPointPosition":{"x":21,"y":62},"snapToGrid":false,"ActionMetadata":{"bffef2bd-e922-4471-9466-b199bb9fbe93":{"position":{"x":1027,"y":44},"useDynamic":false},"fc8bea14-6851-4a91-9a9d-4ffa12763e9a":{"position":{"x":626,"y":48},"useDynamic":false,"queue":{"id":"arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/queue/${ConnectQueueId}","text":"BasicQueue"}},"9e679d1b-f0d2-40a8-ad71-c2118a4f6b5a":{"position":{"x":662,"y":284},"useDynamic":false},"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b":{"position":{"x":1415,"y":281}},"590ad770-653e-4368-9153-ab6801067f10":{"position":{"x":242,"y":43},"useDynamic":false},"1385a539-d538-4304-892b-6e4651ef6862":{"position":{"x":252,"y":324},"conditionMetadata":[{"id":"909b95dd-066a-40ac-a0ab-05e2c05d5f85","value":"1"},{"id":"c31a8352-dcbd-448f-b1b6-d8eafaf25660","value":"9"}],"useDynamic":false,"useLexBotDropdown":true,"useDynamicLexBotArn":false}}},"Actions":[{"Identifier":"bffef2bd-e922-4471-9466-b199bb9fbe93","Transitions":{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","Errors":[{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","ErrorType":"NoMatchingError"},{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","ErrorType":"QueueAtCapacity"}],"Conditions":[]},"Type":"TransferContactToQueue"},{"Identifier":"fc8bea14-6851-4a91-9a9d-4ffa12763e9a","Parameters":{"QueueId":"arn:aws:connect:${AWS::Region}:${AWS::AccountId}:instance/${ConnectInstanceId}/queue/${ConnectQueueId}"},"Transitions":{"NextAction":"bffef2bd-e922-4471-9466-b199bb9fbe93","Errors":[{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","ErrorType":"NoMatchingError"}],"Conditions":[]},"Type":"UpdateContactTargetQueue"},{"Identifier":"9e679d1b-f0d2-40a8-ad71-c2118a4f6b5a","Parameters":{"Text":"Thank
        you for calling.
        Goodbye."},"Transitions":{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","Errors":[],"Conditions":[]},"Type":"MessageParticipant"},{"Identifier":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","Type":"DisconnectParticipant","Parameters":{},"Transitions":{}},{"Identifier":"590ad770-653e-4368-9153-ab6801067f10","Parameters":{"Text":"Hello,
        welcome to our call
        center!"},"Transitions":{"NextAction":"1385a539-d538-4304-892b-6e4651ef6862","Errors":[],"Conditions":[]},"Type":"MessageParticipant"},{"Identifier":"1385a539-d538-4304-892b-6e4651ef6862","Parameters":{"Text":"Please
        press 1 to be speak to our agents or press 9 to terminate this call.
        Thanks!","StoreInput":"False","InputTimeLimitSeconds":"5"},"Transitions":{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","Errors":[{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","ErrorType":"NoMatchingError"},{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","ErrorType":"NoMatchingCondition"},{"NextAction":"afc8f4a2-6cb3-4fa5-bf5c-d0cf9f5b879b","ErrorType":"InputTimeLimitExceeded"}],"Conditions":[{"NextAction":"fc8bea14-6851-4a91-9a9d-4ffa12763e9a","Condition":{"Operator":"Equals","Operands":["1"]}},{"NextAction":"9e679d1b-f0d2-40a8-ad71-c2118a4f6b5a","Condition":{"Operator":"Equals","Operands":["9"]}}]},"Type":"GetParticipantInput"}]}
      Tags:
        - Key: testkey
          Value: testValue
