AWSTemplateFormatVersion: 2010-09-09
Description: Creates an IAM managed policy

#-----------
Parameters:
#-----------
  IAMRole:
    Description: Amazon IAM role (friendly name, not ARN) to attach the policy to
    Type: String

  S3Bucket:
    Description: Amazon S3 bucket
    Type: String

#-----------
Resources:
#-----------
  IAMManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for required for S3 Access
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: 'S3PermissionsBucket'
            Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}'
          - Sid: 'S3PermissionsObject'
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'
      Roles:
        - !Ref IAMRole