AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an IAM role that allows API Gateway to push CloudWatch logs to user's account

#-----------
Resources:
#-----------
  IAMRole: 
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Sid: APIGateway
            Effect: Allow
            Principal: 
              Service: 
                - apigateway.amazonaws.com
            Action: 
              - sts:AssumeRole

  IAMRoleManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy that allows API Gateway to push CloudWatch logs
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: APIGatewayCloudWatchAccess1
            Effect: Allow
            Action: 
              - logs:GetLogEvents
              - logs:PutLogEvents
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*:log-stream:*'
          - Sid: APIGatewayCloudWatchAccess2
            Effect: Allow
            Action: 
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:FilterLogEvents
              - logs:CreateLogGroup
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:*'
      Roles: 
        - !Ref IAMRole

#-----------
Outputs:
#-----------
  IAMRoleArn:
    Value: !GetAtt IAMRole.Arn
    Description: IAM Role Arn